### ISSUE TITLE
Twitch integration problems

### ISSUE THREAD

**Issue by SouDescolado** [WillowChat/Thump#55]
Hello

I tried configuring thump to work with twitch, since twitch uses irc chat. It works fine to send messages/achievements from minecraft>irc. However, I dont see any messages from irc to minecraft.

Also, about the commands, I wanted to know if there is a way to receive an irc message to trigger a command on minecraft, or even say in minecraft (there is a chatdetector block on RandomThings that sends redstone signals every time a player says a specific word)

I am using thump for 1.10.2  (4.03.04) on a single player world. I usually open the world to Lan because I forgot to allow cheats on creation.

**Comment by lopcode** [comment]
This sounds like a Twitch related problem in Warren (the library used to do the IRC stuff) - did you follow a guide for connecting to Twitch that I could follow, to try and reproduce the issue?

**Comment by SouDescolado** [comment]
Here is my irc  config file

```
# Configuration file

~CONFIG_VERSION: 2

connections {

    soudescolado {
        #  [default: ]
        S:Server=irc.chat.twitch.tv

        #  [range: 1 ~ 65535, default: 6697]
        I:Port=6667

        #  [default: thump-server]
        S:Nickname=YOURTWITCHUSERNAME

        #  [default: ]
        S:Channels <
            #THECHANNELYOUWANTTOJOIN
         >

        #  [default: ]
        S:IgnoredNicks <
         >

        #  [default: ]
        S:ServerPassword=oauth:YOUR OAUTHKEYHERE

        auth {

            nickserv {
                #  [default: false]
                B:IdentifyWithNickserv=false

                #  [default: ]
                S:NickservAccount=

                #  [default: ]
                S:NickservPassword=
            }

            sasl {
                #  [default: false]
                B:IdentifyWithSASL=false

                #  [default: ]
                S:SASLAccount=

                #  [default: ]
                S:SASLPassword=
            }

        }

        tls {
            #  [default: true]
            B:UseTLS=false

            #  [default: false]
            B:ForceAcceptCertificates=false

            # Leave blank with 'ForceAcceptCertificates' on to enter the danger zone and forcefully accept all presented certificates [default: ]
            S:ForciblyAcceptedCertificates <
             >
        }

        reconnect {
            #  [default: true]
            B:ShouldReconnectAutomatically=true

            #  [range: 0 ~ 3600, default: 60]
            I:AutomaticReconnectDelaySeconds=60

            #  [range: 1 ~ 5, default: 3]
            I:MaxConsecutiveReconnectAttempts=3
        }

    }

}


events {
    #  [default: true]
    B:ChannelMessage=true

    #  [default: true]
    B:ChannelAction=true
    B:channelAction=true
    B:channelMessage=true
}


##########################################################################################################
# formats
#--------------------------------------------------------------------------------------------------------#
# Formatting tokens: {u} -> user, {c} -> channel, {m} -> message, {s} -> server
##########################################################################################################

formats {
    #  [default: {c}: <{u}> {m}]
    S:ChannelMessage={c}: <{u}> {m}

    #  [default: {c}: * {u} {m}]
    S:ChannelAction={c}: * {u} {m}

    #  [default: IRC network ready: {m}]
    S:NetworkReady=IRC network ready: {m}

    #  [default: IRC network disconnected: {m}]
    S:NetworkDisconnected=IRC network disconnected: {m}
}


general {
    #  [default: true]
    B:LogIRCToServerConsole=true

    # Dumps raw incoming IRC lines to the console using INFO level - leave disabled when you don't need it! [default: false]
    B:LogRawIncomingIRCLinesToConsole=true
}
```


https://twitchapps.com/tmi/ < Is the website that gives the oauth you need to use when you connect

**Comment by SouDescolado** [comment]
I am failing hard to post the code in the right way

**Comment by SouDescolado** [comment]
```
# Configuration file

~CONFIG_VERSION: 1

commands {
    #  [default: !]
    S:Prefix=!

    #  [default: true]
    B:Players=true
}


events {

    minecraft {
        #  [default: true]
        B:PlayerJoined=false

        #  [default: true]
        B:PlayerLeft=false

        #  [default: true]
        B:PlayerAchievement=true

        #  [default: true]
        B:PlayerMessage=false

        #  [default: true]
        B:PlayerMessage=false

        #  [default: true]
        B:PlayerAction=true

        #  [default: true]
        B:PlayerDeath=true

        #  [default: true]
        B:ServerMessage=true

        #  [default: true]
        B:ServerAction=true
    }

}


##########################################################################################################
# formats
#--------------------------------------------------------------------------------------------------------#
# Formatting tokens: {u} -> user, {c} -> channel, {m} -> message, {de} -> contextual death emoji
# Note that only tokens listed in the defaults are supported for each message!
##########################################################################################################

formats {

    minecraft {
        #  [default: <{u}> {m}]
        S:PlayerMessage=<{u}> {m}

        #  [default: * {u} {m}]
        S:PlayerAction=* {u} {m}

        #  [default: {m} ðŸŒŸ]
        S:PlayerAchievement={m} ðŸŒŸ

        #  [default: {m} {de}]
        S:PlayerDeath={m} {de}

        #  [default: {u} has joined the game]
        S:PlayerJoined={u} has joined the game

        #  [default: {u} has left the game]
        S:PlayerLeft={u} has left the game

        #  [default: Players online: {m}]
        S:PlayersOnline=Players online: {m}

        #  [default: There are no players online]
        S:PlayersOnlineNone=There are no players online
    }

}


general {
    # Inserts a zero-width character in to source usernames going from Minecraft to other services - commonly used to prevent unnecessary pings. [default: true]
    B:ObfuscateUserSourceFromMinecraft=true
}


```
This is the config.cfg

**Comment by lopcode** [comment]
I've just tried this locally, and it appears the nickname is strictly case sensitive, and expects lowercasing. Could you try setting your nickname in `irc.cfg` to be lowercase please?

**Comment by SouDescolado** [comment]
My bot name on twitch is BotDescolado, however on the irc.cfg I put the name all lowercase. like         `S:Nickname=botdescolado`

I put in uppercase here just to show where

**Comment by lopcode** [comment]
Ok, I've found a couple of bugs, and I'll try the fixes on my own Twitch channel first.

**Comment by SouDescolado** [comment]
If you need help testing just tell me. You can say on my twitch channel if Im online

**Comment by lopcode** [comment]
I believe this is fixed in Thump-1.10.2-4.3.0.3 - could you try this version please? https://ci.carrot.codes/job/Willow%20Chat/job/Thump/job/feature%252F1.10/lastSuccessfulBuild/artifact/build/libs/Thump-1.10.2-4.3.0.3.jar

If it works for you, I'll upload it to CurseForge.

**Comment by SouDescolado** [comment]
Ill check, A moment please

**Comment by SouDescolado** [comment]
It works! Now I receive the messages from IRC on Minecraft.
It still doesnt detect the words with RandomThings chat detector, but its better than not working. If possible, can you also fix the 1.7 version? I want to use it on infinity evolved too :)

**Comment by lopcode** [comment]
I'm watching your stream, and the bug appears to be fixed, but the chat detector isn't detecting the message because they're sent to players specifically (so, only your client).

Doing it that way is the safest, and I'm not sure there's a way to make messages available to blocks like you want - feel free to open another bug to track it.

**Comment by SouDescolado** [comment]
Is there a way to send commands directly to the game? Like when someone says !weather it does /weather clear?

**Comment by lopcode** [comment]
Not currently. A command system is planned but probably not in the near future. It's made more for server links than Twitch interactivity, but it's nice that the basic chat functionality works!

**Comment by lopcode** [comment]
Also, it would be too much work to backport to 1.7.10, sorry!

**Comment by SouDescolado** [comment]
Thank you o/
